name: ci

on: [push]

jobs:
    run:
        runs-on: ubuntu-latest
        name: install > build > test
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
            - run: yarn
            - run: yarn build
            - run: yarn test
